In [1]:
import pandas as pd

In [2]:
news_json = pd.read_json(r'/home/becode/NLP-project/assets/news_data.json')
news_df = pd.json_normalize(news_json['data'])

In [3]:
news_df.head()

id                                              title  \
0  10813  ZingBox aims for ‘Internet of Trusted Things’,...   
1  10814   AI may help create more sustainable data centres   
2  10815  Why a potential trillion dollar B2B bots indus...   
3  10816  Why companies investing in AI today should exp...   
4  10817  Tencent gears up for greater GPU acceleration ...   

                                             summary authors  \
0  Cybersecurity provider ZingBox has announced t...    None   
1  Enterprise data centre provider Aegis Data arg...    None   
2  From Domino’s Pizza, to Uber, to Bank of Ameri...    None   
3  Organisations investing in artificial intellig...    None   
4  Tencent’s cloud computing services will be bee...    None   

                                                tags  \
0  device\niot\nguardian\napproach\ndevices\nindu...   
1  data\ncentre\nnatural\nnew\ntechnology\nindust...   
2  next\nbig\ngupshup\none\nbusiness\ntech\nimpac...   
3  ai\norganisations\nindustry\nemployees\nexpo\n...   
4  gpu\naccelerators\ngpus\ncloud\nservices\ntesl...   

                                                text  \
0  Cybersecurity provider ZingBox has announced t...   
1  Enterprise data centre provider Aegis Data arg...   
2  From Domino’s Pizza, to Uber, to Bank of Ameri...   
3  Organisations investing in artificial intellig...   
4  Tencent’s cloud computing services will be bee...   

                                                 url  source  \
0  https://artificialintelligence-news.com/2017/0...  AInews   
1  https://artificialintelligence-news.com/2017/0...  AInews   
2  https://artificialintelligence-news.com/2017/0...  AInews   
3  https://artificialintelligence-news.com/2017/0...  AInews   
4  https://artificialintelligence-news.com/2017/0...  AInews   

                 created_at                updated_at        author  \
0  2020-02-05T17:08:34.343Z  2020-02-05T17:08:34.343Z  James Bourne   
1  2020-02-05T17:08:34.355Z  2020-02-05T17:08:34.355Z  James Bourne   
2  2020-02-05T17:08:34.365Z  2020-02-05T17:08:34.365Z  James Bourne   
3  2020-02-05T17:08:34.375Z  2020-02-05T17:08:34.375Z  James Bourne   
4  2020-02-05T17:08:34.385Z  2020-02-05T17:08:34.385Z  James Bourne   

         date  
0  2017-04-25  
1  2017-04-25  
2  2017-04-25  
3  2017-04-25  
4  2017-04-26

In [4]:
news_df['text'][0]

'Cybersecurity provider ZingBox has announced the launch of a new generation of cybersecurity solutions, called IoT Guardian, which focuses on service protection.\n\nThe solution is being claimed as the industry’s first to offer a combination of deep learning algorithms to discern each device’s unique personality and enforce acceptable behaviour. Its self-learning approach continually builds on previous knowledge to discover, detect and defend critical Internet of Things (IoT) services and data while avoiding false positives with 99.9% accuracy.\n\nThe IoT Guardian works differently from traditional IT security solutions. The outmoded IT security focuses only on data protection, and is unable to defend the diverse set of IoT devices that feature a variety of non-standard and customised operating systems. The new IoT Guardian on the other hand is developed on a fully non-disruptive approach that discerns each device’s personality, monitors all activities and enforces trusted behaviour.\

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')

In [7]:
dtm = cv.fit_transform(news_df['text'])

In [8]:
dtm

<1626x18693 sparse matrix of type '<class 'numpy.int64'>'
	with 430418 stored elements in Compressed Sparse Row format>

In [9]:
from sklearn.decomposition import LatentDirichletAllocation

In [10]:
LDA = LatentDirichletAllocation(n_components=12,random_state=42)

In [11]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=12, random_state=42)

# Showing Stored Words

In [12]:
len(cv.get_feature_names())

18693

In [14]:
import random
for i in range(10):
    random_word_id = random.randint(0,18693)
    print(cv.get_feature_names()[random_word_id])

obtains
knob
acquire
flu
brits
subtleties
investigation
heal
brink
sought


## Showing Top Words Per Topic

In [15]:
len(LDA.components_)

12

In [16]:
LDA.components_

array([[ 0.08334172, 23.69277846,  0.08333873, ...,  5.14280669,
         0.08333746,  0.08333463],
       [ 1.22978347, 55.21745536,  0.08333333, ...,  0.0833335 ,
         0.08333341,  2.24895928],
       [ 0.08333693, 39.42812026,  0.08333333, ..., 27.77960887,
         0.08333339,  0.08333334],
       ...,
       [ 0.08334353,  6.6501812 ,  0.08333333, ...,  0.08333354,
         0.08333333,  3.43769152],
       [ 1.66551819, 56.03278536,  0.08333333, ...,  0.08333469,
         0.08333345,  0.0833375 ],
       [ 1.47128493, 20.23780843,  0.08333333, ...,  0.08333496,
         0.08333411,  1.23619556]])

In [17]:
len(LDA.components_[0])

18693

In [18]:
single_topic = LDA.components_[0]

In [19]:
# Returns the indices that would sort this array.
single_topic.argsort()

array([17405,  5407,  4089, ...,   927,   792,  7130])

In [23]:
# Word least representative of this topic
single_topic[17405]

0.08333333333334264

In [22]:
# Word most representative of this topic
single_topic[7130]

723.7467844677382

In [24]:
# Top 10 words for this topic:
single_topic.argsort()[-10:]

array([ 7430,  4542, 14569, 10321,  8186, 12558, 10076,   927,   792,
        7130])

In [25]:
top_word_indices = single_topic.argsort()[-10:]

In [26]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

google
deepmind
said
match
human
play
machine
alphago
ai
game


let's view all the 12 topics found.

In [28]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 20 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-20:]])
    print('\n')

THE TOP 20 WORDS FOR TOPIC #0
['researchers', 'says', 'sedol', 'world', 'just', 'china', 'lee', 'learning', 'players', 'games', 'google', 'deepmind', 'said', 'match', 'human', 'play', 'machine', 'alphago', 'ai', 'game']


THE TOP 20 WORDS FOR TOPIC #1
['different', 'people', 'algorithm', 'using', 'make', 'systems', 'professor', 'like', 'work', 'time', 'research', 'computer', 'new', 'researchers', 'team', 'human', 'mit', 'robots', 'robot', 'says']


THE TOP 20 WORDS FOR TOPIC #2
['work', 'text', 'computer', 'team', 'real', 'used', 'neural', 'art', 'time', 'just', 'learning', 'machine', 'data', 'ai', 'new', 'facebook', 'news', 'fake', 'says', 'like']


THE TOP 20 WORDS FOR TOPIC #3
['job', 'machines', 'make', 'workers', 'time', 'work', 'just', 'future', 'think', 'humans', 'people', 'technology', 'like', 'new', 'jobs', 'artificial', 'world', 'human', 'intelligence', 'ai']


THE TOP 20 WORDS FOR TOPIC #4
['faculty', 'technology', 'learning', 'work', 'institute', 'group', 'artificial', 'sai

### Attaching Discovered Topic Labels to Original Articles

In [29]:
dtm

<1626x18693 sparse matrix of type '<class 'numpy.int64'>'
	with 430418 stored elements in Compressed Sparse Row format>

In [30]:
dtm.shape

(1626, 18693)

In [31]:
len(news_df)

1626

In [32]:
topic_results = LDA.transform(dtm)

In [33]:
topic_results.shape

(1626, 12)

In [34]:
topic_results[0]

array([4.16679405e-04, 4.16685633e-04, 4.16680667e-04, 1.05574248e-01,
       4.16680923e-04, 4.16689119e-04, 4.16684817e-04, 4.16686173e-04,
       7.36782231e-01, 4.16679104e-04, 1.44279113e-01, 1.00309430e-02])

In [35]:
topic_results[0].round(2)

array([0.  , 0.  , 0.  , 0.11, 0.  , 0.  , 0.  , 0.  , 0.74, 0.  , 0.14,
       0.01])

In [36]:
topic_results[0].argmax()

8

This means that our model thinks that the first article belongs to topic #8.



### Combining with Original Data

In [47]:
topic_df = news_df.copy()


In [48]:
topic_df['topic'] = topic_results.argmax(axis=1)

8     435
5     233
6     194
1     176
7     137
3     120
4     108
0      54
10     51
2      46
9      40
11     32
Name: topic, dtype: int64